# Generated by Django 4.2.1 on 2023-05-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0002_remove_account_currencyid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='accountId',
            new_name='companyName',
        ),
    ]
