# Generated by Django 4.2.1 on 2023-05-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0004_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bookindID',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
