# Generated by Django 4.2.1 on 2023-05-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0005_transaction_bookindid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='bookindID',
            new_name='bookingID',
        ),
    ]
