# Generated by Django 4.2.1 on 2023-05-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0006_rename_bookindid_transaction_bookingid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='bookingID',
            new_name='bookingId',
        ),
    ]
