# Generated by Django 4.2.1 on 2023-05-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0007_rename_bookingid_transaction_bookingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bookingId',
            field=models.IntegerField(),
        ),
    ]
