# Generated by Django 4.2.1 on 2023-05-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0008_alter_transaction_bookingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bookingId',
            field=models.IntegerField(null=True),
        ),
    ]
